# Automatically generated by wireguard-web
{% for peer in peers %}{% if peer.is_trusted %} {{ date }}
# {{ peer.username }}
[Peer]
PublicKey = {{ peer.pubkey }}
AllowedIPs = {{ peer.ip_address|int2ip }}{% if peer.ipv6_address %}, {{ peer.ipv6_address }}{% endif %}
{% endif %}{% endfor %}
